stages:
  - test
  - connect-aws

test:
  stage: test
  image: python:3.10.12
  variables:
    ALLOWED_HOSTS: "*"
    SQLITE_DIR: "$BASE_DIR/docker/db_empty.sqlite3"
    DEBUG: 'true'
  script:
    - ls
    - pip install -r requirements.txt
    - python3 manage.py test

assume role:
  stage: connect-aws
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
