# Generated by Django 5.0.1 on 2024-01-24 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('stored_objects', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('stored_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stored_objects.storedobjects')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
    ]
