# Generated by Django 5.0.1 on 2024-01-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_record', '0001_initial'),
        ('stored_objects', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='stored_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stored_objects.storedobjects'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.work'),
        ),
    ]
