# Generated by Django 5.0.1 on 2024-01-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('purchase_record', '0003_alter_purchaserecord_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
