FROM python:3.10.12

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --progress-bar off --no-cache-dir --upgrade pip

RUN pip install --progress-bar off --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
