# Generated by Django 5.0.1 on 2024-01-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense_record', '0001_initial'),
        ('purchase_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='purchase_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_record.purchaserecord'),
        ),
    ]
