# Generated by Django 5.0.1 on 2024-01-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0003_expenserecord_work'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.work'),
        ),
    ]
