# Generated by Django 5.0.1 on 2024-01-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0004_alter_expenserecord_work'),
        ('object', '0003_alter_material_work_alter_tool_work'),
        ('organization', '0001_initial'),
        ('purchase_record', '0003_alter_purchaserecord_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.material'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='purchase_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_record.purchaserecord'),
        ),
    ]
