# Generated by Django 5.0.1 on 2024-01-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=50)),
                ('last_names', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
    ]
