# Generated by Django 5.0.1 on 2024-01-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accion_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionrecord',
            name='type',
            field=models.CharField(choices=[('entry', 'Entry'), ('return', 'Return')], max_length=50, null=True),
        ),
    ]
