# Generated by Django 5.0.1 on 2024-02-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accion_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionrecord',
            name='quantity_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accionrecord',
            name='type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('return', 'Return')], max_length=8, null=True),
        ),
    ]
