# Generated by Django 5.0.1 on 2024-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accion_record', '0002_alter_accionrecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionrecord',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
